# Generated by Django 5.0.4 on 2024-04-30 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 17, 30, 59, 564870, tzinfo=datetime.timezone.utc)),
        ),
    ]
