# Generated by Django 5.0.4 on 2024-04-30 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_post_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
